spring:
   datasource:
      hikari:
         connection-timeout: 3000
         max-lifetime: 580000
         connection-test-query: SELECT 1
         validation-timeout: 3000
         maximum-pool-size: 10
         driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
         jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
         username: test
         password: test1234